use super::*;

pub(crate) fn router(state: AppState) -> Router<AppState> {
    let provider_auth_callback_routes = Router::new()
        .route(
            "/api/v1/admin/providers/auth/callback",
            post(complete_provider_auth_callback),
        )
        .route(
            "/api/v1/admin/providers/{id}/auth/{flow_id}/complete",
            post(complete_provider_auth_callback_for_flow),
        )
        .layer(DefaultBodyLimit::max(MAX_PROVIDER_AUTH_CALLBACK_BODY_BYTES));
    let protected = Router::new()
        .route("/api/v1/admin/overview", get(overview))
        .route(
            "/api/v1/admin/overview/upstream-events",
            get(providers::upstream_events),
        )
        .route("/api/v1/admin/metrics", get(prometheus_metrics))
        .route("/api/v1/admin/provider-presets", get(list_provider_presets))
        .route(
            "/api/v1/admin/providers",
            get(providers::list_providers).post(providers::create_provider),
        )
        .route(
            "/api/v1/admin/providers/{id}/keys",
            get(providers::list_provider_keys).post(providers::create_provider_key),
        )
        .route(
            "/api/v1/admin/providers/{id}/keys/{key_id}",
            put(providers::update_provider_key).delete(providers::delete_provider_key),
        )
        .route(
            "/api/v1/admin/providers/{id}/keys/{key_id}/order",
            put(providers::swap_provider_key_order),
        )
        .route(
            "/api/v1/admin/providers/{id}/keys/{key_id}/usage",
            get(providers::provider_key_usage).post(providers::refresh_provider_key_usage),
        )
        .route(
            "/api/v1/admin/providers/{id}/keys/{key_id}/usage-budget",
            put(providers::update_provider_usage_budget),
        )
        .route(
            "/api/v1/admin/providers/{id}/usage",
            get(providers::provider_usage).post(providers::refresh_provider_usage),
        )
        .route(
            "/api/v1/admin/providers/{id}/thinking-settings",
            put(providers::update_provider_thinking_settings),
        )
        .route(
            "/api/v1/admin/providers/{id}/key-strategy",
            put(providers::update_provider_key_strategy),
        )
        .route(
            "/api/v1/admin/providers/{id}",
            put(providers::update_provider).delete(providers::delete_provider),
        )
        .route(
            "/api/v1/admin/providers/{id}/models",
            get(providers::list_provider_models).delete(providers::delete_provider_model),
        )
        .route(
            "/api/v1/admin/providers/{id}/models/search",
            get(providers::search_provider_models),
        )
        .route(
            "/api/v1/admin/providers/{id}/models/routing",
            get(providers::list_provider_model_routing)
                .put(providers::update_provider_model_routing),
        )
        .route(
            "/api/v1/admin/providers/{id}/models/import",
            post(providers::import_provider_models),
        )
        .route(
            "/api/v1/admin/providers/{id}/models/manual",
            post(providers::add_manual_provider_model),
        )
        .route(
            "/api/v1/admin/providers/{id}/quota",
            get(providers::provider_quota).put(providers::update_provider_quota_target),
        )
        .route(
            "/api/v1/admin/providers/{id}/auth/start",
            post(start_provider_auth),
        )
        .route(
            "/api/v1/admin/providers/{id}/auth/{flow_id}",
            get(provider_auth_status),
        )
        .route(
            "/api/v1/admin/providers/{id}/auth/{flow_id}/poll",
            post(provider_auth::provider_auth_poll),
        )
        .merge(provider_auth_callback_routes)
        .route(
            "/api/v1/admin/providers/{id}/api-key-auth/start",
            post(provider_api_key_auth::start),
        )
        .route(
            "/api/v1/admin/providers/{id}/api-key-auth/{flow_id}",
            get(provider_api_key_auth::status),
        )
        .route(
            "/api/v1/admin/providers/{id}/api-key-auth/{flow_id}/apply",
            post(provider_api_key_auth::apply),
        )
        // Kept as aliases so existing dashboard builds and API clients keep working.
        .route(
            "/api/v1/admin/providers/{id}/codex/oauth/start",
            post(start_provider_auth),
        )
        .route(
            "/api/v1/admin/providers/{id}/codex/oauth/{flow_id}",
            get(provider_auth_status),
        )
        .route(
            "/api/v1/admin/combos",
            get(combos::list_combos).post(combos::create_combo),
        )
        .route(
            "/api/v1/admin/combos/provider-options",
            get(combos::list_provider_options),
        )
        .route(
            "/api/v1/admin/combos/{id}",
            put(combos::update_combo).delete(combos::delete_combo),
        )
        // Retain the legacy management endpoints for existing dashboard builds.
        .route(
            "/api/v1/admin/routes",
            get(combos::list_routes).post(combos::create_route),
        )
        .route(
            "/api/v1/admin/routes/{id}",
            put(combos::update_route).delete(combos::delete_route),
        )
        .route("/api/v1/admin/models", get(combos::list_models))
        .route("/api/v1/admin/models/test", post(model_probes::test_models))
        .route("/api/v1/admin/requests", get(request_logs::list_requests))
        .route(
            "/api/v1/admin/requests/events",
            get(request_logs::request_events),
        )
        .route("/api/v1/admin/statistics", get(statistics::get_statistics))
        .route(
            "/api/v1/admin/api-keys/{id}/statistics",
            get(statistics::get_api_key_statistics),
        )
        .route(
            "/api/v1/admin/request-logs",
            delete(request_logs::delete_request_logs),
        )
        .route("/api/v1/admin/settings", get(settings::settings))
        .route(
            "/api/v1/admin/settings/update-check",
            get(update_check::check_for_updates),
        )
        .route(
            "/api/v1/admin/settings/resource-limits",
            get(settings::get_gateway_resource_limits)
                .put(settings::update_gateway_resource_limits),
        )
        .route(
            "/api/v1/admin/settings/operational",
            get(settings::get_operational_settings).put(settings::update_operational_settings),
        )
        .route(
            "/api/v1/admin/settings/operational/reset",
            post(settings::reset_operational_settings),
        )
        .route(
            "/api/v1/admin/settings/output-styles",
            get(settings::get_output_styles).put(settings::update_output_styles),
        )
        .route(
            "/api/v1/admin/settings/output-styles/reset",
            post(settings::reset_output_styles),
        )
        .route(
            "/api/v1/admin/database/export",
            get(database::export_database),
        )
        .route(
            "/api/v1/admin/database/import",
            post(database::import_database),
        )
        .route(
            "/api/v1/admin/auth/reauth",
            post(sessions::reauthenticate).route_layer(middleware::from_fn_with_state(
                state.clone(),
                rate_limit_admin_login,
            )),
        )
        .route(
            "/api/v1/admin/settings/admin-password",
            put(auth::change_admin_password),
        )
        .route(
            "/api/v1/admin/api-keys",
            get(api_keys::list_api_keys).post(api_keys::create_api_key),
        )
        .route(
            "/api/v1/admin/api-keys/{id}",
            delete(api_keys::delete_api_key),
        )
        .route_layer(middleware::from_fn_with_state(state.clone(), require_admin));

    Router::new()
        .route(
            "/api/v1/admin/auth/login",
            post(auth::admin_login).route_layer(middleware::from_fn_with_state(
                state.clone(),
                rate_limit_admin_login,
            )),
        )
        .route("/api/v1/admin/auth/refresh", post(sessions::refresh))
        .route("/api/v1/admin/auth/logout", post(sessions::logout))
        .merge(protected)
}
